# Generated by Django 2.2 on 2019-06-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('isPublic', models.BooleanField(default=False)),
                ('viewCount', models.BigIntegerField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('recommendationList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RecommendationList')),
            ],
        ),
    ]
