# Generated by Django 2.2 on 2019-06-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190622_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationlist',
            name='viewCount',
        ),
        migrations.AddField(
            model_name='recommendationlist',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationlist',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='recommendationlist',
            name='requisites',
            field=models.TextField(default='', null=True),
        ),
    ]
