# Generated by Django 2.2 on 2019-07-08 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20190624_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Resource',
        ),
        migrations.RenameModel(
            old_name='RecommendationList',
            new_name='ResourceList',
        ),
    ]
