# Generated by Django 2.2 on 2019-07-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190708_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelist',
            old_name='user',
            new_name='creator',
        ),
    ]
