# Generated by Django 2.2 on 2019-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190709_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelist',
            name='title',
            field=models.CharField(default='Untitled list', max_length=255, null=True),
        ),
    ]
