# Generated by Django 2.2 on 2019-07-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_resource_numvotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='numVotes',
            new_name='votesCount',
        ),
    ]
