# Generated by Django 2.2 on 2019-07-11 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20190710_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to='main.ResourceList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
