# Generated by Django 2.2 on 2019-07-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bookmarkedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='resourceList',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.ResourceList'),
            preserve_default=False,
        ),
    ]
