# Generated by Django 2.2 on 2019-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_resource_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='estimateMinutes',
            field=models.FloatField(null=True),
        ),
    ]
