# Generated by Django 2.2 on 2019-08-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_resource_estimateminutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Outros', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='resourcelist',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='resourceLists', to='main.Category'),
            preserve_default=False,
        ),
    ]
