# Generated by Django 2.2 on 2019-08-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190816_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.Category'),
        ),
    ]
