# Generated by Django 2.2 on 2019-08-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_category_parentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
