# Generated by Django 2.2 on 2019-08-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(default='', null=True),
        ),
    ]
